sudo: false
language: node_js
node_js:
  - "4.1"
env:
  global:
    # Please get your own free key if you want to test yourself
    - BROWSERSTACK_USERNAME: kitsonkelly1
    - BROWSERSTACK_ACCESS_KEY: uEoWrS6XmTX4XSpxUm6Q
    - SAUCE_USERNAME: core-ts-ci
    - SAUCE_ACCESS_KEY: 735b17e8-adcd-436a-bc5e-f5bec5e91a64
cache:
  directories:
    - node_modules
install:
  - "travis_retry npm install grunt-cli"
  - "travis_retry npm install"
script:
  - "grunt"
  - "grunt intern:node --combined"
  - "grunt intern:saucelabs --combined"
  - "grunt remapIstanbul:ci"
  - "grunt uploadCoverage"
